<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <OutputType>Library</OutputType>
    <AssemblyName>UziStormwerkzElcanScope</AssemblyName>
    <RootNamespace>Xidong.UZI.ELCAN</RootNamespace>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SPTarkov.Common" Version="4.0.13" />
    <PackageReference Include="SPTarkov.DI" Version="4.0.13" />
    <PackageReference Include="SPTarkov.Server.Core" Version="4.0.13" />
  </ItemGroup>

</Project>
