<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>UziStormwerkzElcanScope</AssemblyName>
    <RootNamespace>Xidong.UZI.ELCAN</RootNamespace>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="SPTarkov.DI">
      <HintPath>ref/SPTarkov.DI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SPTarkov.Common">
      <HintPath>ref/SPTarkov.Common.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SPTarkov.Server.Core">
      <HintPath>ref/SPTarkov.Server.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SemanticVersioning">
      <HintPath>ref/SemanticVersioning.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SPT.Server">
      <HintPath>ref/SPT.Server.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
